/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as RejectedRouteImport } from './routes/rejected'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as CategoryNameRouteImport } from './routes/category.$name'
import { Route as SSourceIdRouteImport } from './routes/s.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectedRoute = RejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SSourceIdRoute = SSourceIdRouteImport.update({
  id: '/s/$sourceId',
  path: '/s/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inventory': typeof InventoryRoute
  '/pending': typeof PendingRoute
  '/rejected': typeof RejectedRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/c/$slug': typeof CSlugRoute
  '/category/$name': typeof CategoryNameRoute
  '/s/$sourceId': typeof SSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inventory': typeof InventoryRoute
  '/pending': typeof PendingRoute
  '/rejected': typeof RejectedRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/c/$slug': typeof CSlugRoute
  '/category/$name': typeof CategoryNameRoute
  '/s/$sourceId': typeof SSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/inventory': typeof InventoryRoute
  '/pending': typeof PendingRoute
  '/rejected': typeof RejectedRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/c/$slug': typeof CSlugRoute
  '/category/$name': typeof CategoryNameRoute
  '/s/$sourceId': typeof SSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/inventory'
    | '/pending'
    | '/rejected'
    | '/search'
    | '/sources'
    | '/c/$slug'
    | '/category/$name'
    | '/s/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/inventory'
    | '/pending'
    | '/rejected'
    | '/search'
    | '/sources'
    | '/c/$slug'
    | '/category/$name'
    | '/s/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/inventory'
    | '/pending'
    | '/rejected'
    | '/search'
    | '/sources'
    | '/c/$slug'
    | '/category/$name'
    | '/s/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  InventoryRoute: typeof InventoryRoute
  PendingRoute: typeof PendingRoute
  RejectedRoute: typeof RejectedRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  CSlugRoute: typeof CSlugRoute
  CategoryNameRoute: typeof CategoryNameRoute
  SSourceIdRoute: typeof SSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejected': {
      id: '/rejected'
      path: '/rejected'
      fullPath: '/rejected'
      preLoaderRoute: typeof RejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$name': {
      id: '/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$sourceId': {
      id: '/s/$sourceId'
      path: '/s/$sourceId'
      fullPath: '/s/$sourceId'
      preLoaderRoute: typeof SSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  InventoryRoute: InventoryRoute,
  PendingRoute: PendingRoute,
  RejectedRoute: RejectedRoute,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  CSlugRoute: CSlugRoute,
  CategoryNameRoute: CategoryNameRoute,
  SSourceIdRoute: SSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
