/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/cards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Cards
     * @description Lists card tiles with optional filters and keyset cursor.
     */
    get: operations["list_cards_api_cards_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cards/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Card
     * @description Retrieves full card details including markdown body without notes, and notes section.
     */
    get: operations["get_card_api_cards__slug__get"];
    /**
     * Edit Card
     * @description Updates editable frontmatter and Notes under write lock, guarding with base_hash.
     */
    put: operations["edit_card_api_cards__slug__put"];
    post?: never;
    /**
     * Delete Card
     * @description Rejects a card, removing it from library and logging to rejected.md.
     */
    delete: operations["delete_card_api_cards__slug__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cards/{slug}/links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Links
     * @description Retrieves backlinks, mentioned_by, and outgoing links for a card.
     */
    get: operations["get_links_api_cards__slug__links_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Sources
     * @description Retrieves paginated source list with filters.
     */
    get: operations["list_sources_api_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{id}/video": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Source Video
     * @description Streams video file supporting HTTP Range requests.
     */
    get: operations["get_source_video_api_sources__id__video_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{id}/thumb": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Source Thumb
     * @description Returns poster thumbnail image.
     */
    get: operations["get_source_thumb_api_sources__id__thumb_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Source
     * @description Retrieves full source metadata, parsed source.md, and linked cards.
     */
    get: operations["get_source_api_sources__id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources/{id}/stage": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            stage: "fetched" | "analyzed" | "triaged";
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SourceDetail"];
          };
        };
      };
    };
    trace?: never;
  };
  "/api/sources/{id}/recheck": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SourceDetail"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Pending
     * @description Lists pending link requests from pending.md.
     */
    get: operations["get_pending_api_pending_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pending/{id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve Pending Item
     * @description Resolves a pending item by attaching the obtained destination URL.
     */
    post: operations["resolve_pending_item_api_pending__id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pending/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Pending Item
     * @description Drops a pending item (no-op if already gone).
     */
    delete: operations["delete_pending_item_api_pending__id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/pending/{id}/recheck": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Recheck Pending Item
     * @description Re-runs the Instagram fetch for a blocked item; success drops it from pending.
     */
    post: operations["recheck_pending_item_api_pending__id__recheck_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/rejects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Rejects
     * @description Retrieves all rejected items.
     */
    get: operations["get_rejects_api_rejects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/rejects/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Reject
     * @description Un-rejects an item, removing it from rejected.md.
     */
    delete: operations["delete_reject_api_rejects__key__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/inventory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Inventory
     * @description Lists all scanned and manual inventory items.
     */
    get: operations["get_inventory_api_inventory_get"];
    put?: never;
    /**
     * Add Inventory
     * @description Adds a new manual inventory entry to inventory/manual/tools.md.
     */
    post: operations["add_inventory_api_inventory_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Metadata
     * @description Returns categories, tags, counts, and application version.
     */
    get: operations["get_metadata_api_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/graph": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Graph Data
     * @description Returns nodes and edges for global graph or centered neighborhood.
     */
    get: operations["get_graph_data_api_graph_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search
     * @description Searches cards using SQLite FTS5 with custom highlight snippets.
     */
    get: operations["search_api_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/reindex": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger Reindex
     * @description Rebuilds the entire SQLite search index from markdown files.
     */
    post: operations["trigger_reindex_api_reindex_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Sse Events
     * @description Subscribes to live Server-Sent Events from the library watcher.
     */
    get: operations["sse_events_api_events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/{rest_of_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Api Not Found */
    get: operations["api_not_found_api__rest_of_path__get"];
    /** Api Not Found */
    put: operations["api_not_found_api__rest_of_path__put"];
    /** Api Not Found */
    post: operations["api_not_found_api__rest_of_path__post"];
    /** Api Not Found */
    delete: operations["api_not_found_api__rest_of_path__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Card
     * @description Frontmatter metadata for an item card.
     */
    Card: {
      /**
       * Schema
       * @default 1
       */
      schema: number;
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Category */
      category: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "repo" | "model" | "skill" | "plugin" | "mcp" | "tool" | "ui_ref" | "practice" | "link";
      /** Tags */
      tags?: string[];
      /**
       * Added
       * Format: date
       */
      added: string;
      /** Url */
      url?: string | null;
      /** Sources */
      sources?: string[];
      /** Facts */
      facts?: {
        [key: string]: unknown;
      };
      /** Features */
      features?: string[];
      /** Overlaps */
      overlaps?: string[];
      /** Bucket */
      bucket?: ("try-now" | "later" | "upgrade" | "inspiration") | null;
    };
    /** CardDetail */
    CardDetail: {
      /** Slug */
      slug: string;
      card: components["schemas"]["Card"];
      /** Body */
      body: string;
      /** Notes */
      notes: string;
      /** Hash */
      hash: string;
      /** Resolved */
      resolved?: {
        [key: string]: string;
      };
    };
    /** CardLinks */
    CardLinks: {
      /** Backlinks */
      backlinks?: {
        [key: string]: string;
      }[];
      /** Mentioned By */
      mentioned_by?: {
        [key: string]: string;
      }[];
      /** Outgoing */
      outgoing?: {
        [key: string]: string;
      }[];
    };
    /** CardPatch */
    CardPatch: {
      /** Base Hash */
      base_hash: string;
      /** Category */
      category?: string | null;
      /** Kind */
      kind?:
        | ("repo" | "model" | "skill" | "plugin" | "mcp" | "tool" | "ui_ref" | "practice" | "link")
        | null;
      /** Tags */
      tags?: string[] | null;
      /** Notes */
      notes?: string | null;
    };
    /** CardRejectRequest */
    CardRejectRequest: {
      /** Reason */
      reason: string;
    };
    /** CardTile */
    CardTile: {
      /** Key */
      key: string;
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Category */
      category: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "repo" | "model" | "skill" | "plugin" | "mcp" | "tool" | "ui_ref" | "practice" | "link";
      /** Added */
      added: string;
      /** Url */
      url?: string | null;
      /** Hash */
      hash: string;
      /** Thumb Url */
      thumb_url?: string | null;
      /** Platform */
      platform?: string | null;
      /** Tags */
      tags?: string[];
      /** Bucket */
      bucket?: ("try-now" | "later" | "upgrade" | "inspiration") | null;
    };
    /** CategoryMeta */
    CategoryMeta: {
      /** Name */
      name: string;
      /** Color */
      color: string;
      /**
       * Count
       * @default 0
       */
      count: number;
    };
    /** GraphData */
    GraphData: {
      /** Nodes */
      nodes?: components["schemas"]["GraphNode"][];
      /** Edges */
      edges?: components["schemas"]["GraphEdge"][];
    };
    /** GraphEdge */
    GraphEdge: {
      /** Source */
      source: string;
      /** Target */
      target: string;
      /**
       * Type
       * @enum {string}
       */
      type: "wikilink" | "source" | "overlap";
    };
    /** GraphNode */
    GraphNode: {
      /** Id */
      id: string;
      /** Label */
      label: string;
      /** Category */
      category: string;
      /** Kind */
      kind: string;
      /**
       * Size
       * @default 10
       */
      size: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InventoryAddRequest */
    InventoryAddRequest: {
      /** Text */
      text: string;
    };
    /**
     * InventoryEntry
     * @description An installed agent tool, model, or manually recorded inventory item.
     */
    InventoryEntry: {
      /** Key */
      key?: string | null;
      /** Name */
      name: string;
      /** Kind */
      kind: string;
      /** Origin */
      origin: string;
    };
    /**
     * Mention
     * @description A mentioned entity in a source document.
     */
    Mention: {
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Url */
      url?: string | null;
      /** At */
      at?: string | null;
    };
    /** MetaCounts */
    MetaCounts: {
      /** Cards */
      cards: number;
      /** Sources */
      sources: number;
      /** Pending */
      pending: number;
      /** Rejected */
      rejected: number;
      /** Inventory */
      inventory: number;
    };
    /** MetaResponse */
    MetaResponse: {
      /** Categories */
      categories: components["schemas"]["CategoryMeta"][];
      /** Tags */
      tags: components["schemas"]["TagMeta"][];
      counts: components["schemas"]["MetaCounts"];
      /** Version */
      version: string;
    };
    /** Page[CardTile] */
    Page_CardTile_: {
      /** Items */
      items: components["schemas"]["CardTile"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /** Page[SourceRow] */
    Page_SourceRow_: {
      /** Items */
      items: components["schemas"]["SourceRow"][];
      /** Next Cursor */
      next_cursor?: string | null;
    };
    /**
     * PendingItem
     * @description A pending item requiring follow-up (e.g. comment-for-link CTA or blocked fetch).
     */
    PendingItem: {
      /** Id */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "cta" | "blocked";
      /** Source Key */
      source_key?: string | null;
      /** Instruction */
      instruction: string;
      /** Url */
      url?: string | null;
      /**
       * Status
       * @default open
       * @enum {string}
       */
      status: "open" | "ready";
      /**
       * Added
       * Format: date
       */
      added: string;
    };
    /** PendingResolveRequest */
    PendingResolveRequest: {
      /** Url */
      url: string;
    };
    /**
     * RejectEntry
     * @description A rejected item entry.
     */
    RejectEntry: {
      /** Key */
      key: string;
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Reason */
      reason: string;
    };
    /** SearchHit */
    SearchHit: {
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /** Category */
      category: string;
      /** Kind */
      kind: string;
      /** Snippet */
      snippet: string;
    };
    /** SourceDetail */
    SourceDetail: {
      source: components["schemas"]["SourceDoc"];
      /** Video Url */
      video_url?: string | null;
      /** Thumb Url */
      thumb_url?: string | null;
      /** Cards */
      cards?: {
        [key: string]: string;
      }[];
    };
    /**
     * SourceDoc
     * @description A captured source record (e.g. Instagram reel, GitHub repo).
     */
    SourceDoc: {
      /** Key */
      key: string;
      /** Platform */
      platform: string;
      /** Creator */
      creator?: string | null;
      /** Url */
      url: string;
      /** Stage */
      stage: string;
      /** Engine */
      engine?: string | null;
      /** Fetched At */
      fetched_at?: string | null;
      /** Caption */
      caption?: string | null;
      /** Summary */
      summary?: string | null;
      /** Transcript */
      transcript?: string | null;
      /** On Screen Text */
      on_screen_text?: string[];
      /** Mentions */
      mentions?: components["schemas"]["Mention"][];
      /** Cta */
      cta?: {
        [key: string]: unknown;
      } | null;
      /** Video */
      video?: string | null;
      /** Thumb */
      thumb?: string | null;
    };
    /** SourceRow */
    SourceRow: {
      /** Id */
      id: string;
      /** Platform */
      platform: string;
      /** Creator */
      creator?: string | null;
      /** Url */
      url: string;
      /** Stage */
      stage: string;
      /** Has Video */
      has_video: boolean;
      /** Has Thumb */
      has_thumb: boolean;
      /** Video Url */
      video_url?: string | null;
      /** Thumb Url */
      thumb_url?: string | null;
      /** Fetched At */
      fetched_at?: string | null;
    };
    /** TagMeta */
    TagMeta: {
      /** Tag */
      tag: string;
      /** Count */
      count: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_cards_api_cards_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
        category?: string | null;
        kind?:
          | (
              | "repo"
              | "model"
              | "skill"
              | "plugin"
              | "mcp"
              | "tool"
              | "ui_ref"
              | "practice"
              | "link"
            )
          | null;
        tag?: string | null;
        bucket?: ("try-now" | "later" | "upgrade" | "inspiration") | null;
        creator?: string | null;
        since?: string | null;
        until?: string | null;
        has_video?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_CardTile_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_card_api_cards__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_card_api_cards__slug__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_card_api_cards__slug__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CardRejectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RejectEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_links_api_cards__slug__links_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CardLinks"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sources_api_sources_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
        platform?: string | null;
        creator?: string | null;
        stage?: string | null;
        has_video?: boolean | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_SourceRow_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_video_api_sources__id__video_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_thumb_api_sources__id__thumb_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_source_api_sources__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_pending_api_pending_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PendingItem"][];
        };
      };
    };
  };
  resolve_pending_item_api_pending__id__resolve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PendingResolveRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PendingItem"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_pending_item_api_pending__id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recheck_pending_item_api_pending__id__recheck_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_rejects_api_rejects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RejectEntry"][];
        };
      };
    };
  };
  delete_reject_api_rejects__key__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_inventory_api_inventory_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryEntry"][];
        };
      };
    };
  };
  add_inventory_api_inventory_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InventoryAddRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryEntry"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_metadata_api_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetaResponse"];
        };
      };
    };
  };
  get_graph_data_api_graph_get: {
    parameters: {
      query?: {
        center?: string | null;
        depth?: number;
        category?: string | null;
        edge_type?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GraphData"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_api_search_get: {
    parameters: {
      query: {
        q: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchHit"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  trigger_reindex_api_reindex_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  sse_events_api_events_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  api_not_found_api__rest_of_path__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rest_of_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_not_found_api__rest_of_path__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rest_of_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_not_found_api__rest_of_path__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rest_of_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_not_found_api__rest_of_path__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rest_of_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
